apiVersion: apps/v1
kind: Deployment
metadata:
  name:  travel-agency-app
  namespace: default  # Or whatever namespace you're using
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  travel-agency-app
  template:
    metadata:
      labels:
        app:  travel-agency-app
    spec:
      containers:
      - name:  travel-agency-app
        image: travel-agency-app
        ports:
        - containerPort: 80
