apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-travel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-travel-app
  template:
    metadata:
      labels:
        app: react-travel-app
    spec:
      containers:
      - name: travel-agency-app
        image: sholly333/travel-agency-app:latest
        ports:
        - containerPort: 80
