apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-app
  namespace: travel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travel-app
  template:
    metadata:
      labels:
        app: travel-app
    spec:
      containers:
        - name: travel-app
          image: sholly333/travel-app:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: travel-app-service
  namespace: travel-app
spec:
  selector:
    app: travel-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer